name: crud_despesas
description: CRUD em lista de despesas.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_widget_from_html: ^0.15.2
  diacritic: ^0.1.3
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.ttf
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 700
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 300
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-Italic.ttf
          style: italic
        - asset: assets/fonts/Satoshi-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Satoshi-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Satoshi-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Satoshi-BlackItalic.ttf
          weight: 900
          style: italic
